[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
authors = [
    {name = "Frederic Escudie", email = "escudie.frederic@iuct-oncopole.fr"}
]
description = "Scripts for easily process NGS data from medical centers. This package contains several aggregators, converters, filters, wrappers, etc."
dependencies = [
    "scipy == 1.11.3",
    "pysam == 0.23.3",
    "anacore == 2.12.1",
    "scikit-learn == 1.3.2"
]
dynamic = ["version"]
keywords = ["bio", "NGS"]
license.text = "GNU GPL v3"
name = "anacore-utils"
readme = "README.md"
requires-python = ">=3.10"

[project.urls]
Homepage = "https://github.com/bialimed/anacore-utils"
Repository = "https://github.com/bialimed/anacore-utils"

[tool.setuptools.packages.find]
where = ['bin']