{% set version = "3.6.0" %}
# Dependencies versions
{% set anacore_version = "=2.12.1" %}
{% set pysam_version = "=0.18.0" %}
{% set python_version = ">=3.5" %}
{% set scipy_version = "=1.7.3" %}
{% set sklearn_version = "=1.1.2" %}

package:
  name: anacore-utils
  version: {{ version }}

source:
  git_url: https://github.com/bialimed/anacore-utils
  git_rev: {{ version }}

build:
  number: 1
  script: ${PYTHON} setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python {{ python_version }}
    - setuptools
  run:
    - python {{ python_version }}
    - anacore {{ anacore_version }}
    - scipy {{ scipy_version }}
    - scikit-learn {{ sklearn_version }}
    - pysam {{ pysam_version }}

test:
  imports:
    - scipy
    - pysam
    - requests
    - anacore
  commands:
    - mergeCoOccurVar.py -h
    - distToHC.py -h
    - fixHGVSMutalyzer.py -h
    - microsatSklearnClassify.py -h

about:
  summary: Scripts for easily process NGS data from medical centers. This package contains several aggregators, converters, filters, wrappers, etc.
  license: GNU GPL v3
  home: https://github.com/bialimed/anacore-utils
  doc_source_url: https://github.com/bialimed/anacore-utils/blob/{{ version }}/README.md
